version: '3.4'
services:
  mysql:
    container_name: over_scrape_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file:
      - ./.env
  phpmyadmin:
    container_name: over_scrape_phpmyadmin
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./.env
